export const appCopy = {
  "en-US": {
    tagline: "How many tokens have you burned today?",
    perHour: "/ hour",
    last7Days: "Last 7 Days",
    whereItBurns: "Where It Burns",
    connected: "Connected",
    recentSessions: "Recent Sessions",
    noData: "Waiting for first scan…",
    trend30d: "30-Day Trend",
    monthContext: "30-Day Context",
    avgDay: "avg / day",
    weekTotal: "7-day total",
    monthTotal: "30-day total",
    monthPeak: "30-day peak",
    weekPeak: (label) => `Peak on ${label}`,
    monthDelta: (delta) => `This week ${delta} vs 30-day pace`,
    monthFlat: "This week is tracking near the 30-day pace",
    todayCost: (cost) => `about ${cost} today`,
    estimatedCost: (cost) => `~ ${cost}`,
    pricingPending: "pricing pending",
    sourceHistory: "Source History",
    backToOverview: "Back to overview",
    sourceState: "Status",
    pricingCoverage: "Pricing",
    summaryWindows: "Summary Windows",
    weeklyBreakdown: "Weekly Breakdown",
    monthlyBreakdown: "Monthly Breakdown",
    periodLabel: "Period",
    tokensLabel: "Tokens",
    sessionsLabel: "Sessions",
    activeDaysLabel: "Active days",
    peakDayLabel: "Peak day",
    shareLabel: "Exact share",
    sortByLabel: "Sort",
    sortRecent: "Recent",
    sortTokens: "Tokens",
    sortCost: "Cost",
    subagentsLabel: (count) => `${count} ${count === 1 ? "subagent" : "subagents"}`,
    hideSubagents: "Hide subagents",
    subagentTag: (label) => (label ? `Subagent · ${label}` : "Subagent"),
    billingTitle: "Billing State",
    billingUsage: "Usage",
    billingUpdated: "Updated",
    sourceUnavailable: "Source snapshot unavailable",
    noSourceSessions: "No indexed sessions for this source yet",
    refresh: "Refresh",
    refreshing: "Scanning…",
    lastScan: (t) => `Last scan ${t}`,
    waitingScan: "Waiting for first scan",
    refreshFailed: "Refresh failed — will retry automatically"
  },
  "zh-CN": {
    tagline: "你今天已经烧掉多少 token？",
    perHour: "/ 小时",
    last7Days: "近 7 天",
    whereItBurns: "烧在哪里",
    connected: "数据源",
    recentSessions: "最近会话",
    noData: "等待首次扫描…",
    trend30d: "30 天趋势",
    monthContext: "30 天背景",
    avgDay: "日均",
    weekTotal: "7 天总量",
    monthTotal: "30 天总量",
    monthPeak: "30 天峰值",
    weekPeak: (label) => `峰值出现在 ${label}`,
    monthDelta: (delta) => `这周较 30 天节奏 ${delta}`,
    monthFlat: "这周和 30 天节奏基本持平",
    todayCost: (cost) => `今天大约 ${cost}`,
    estimatedCost: (cost) => `约 ${cost}`,
    pricingPending: "价格待补全",
    sourceHistory: "来源历史",
    backToOverview: "返回总览",
    sourceState: "状态",
    pricingCoverage: "计费",
    summaryWindows: "时间窗口",
    weeklyBreakdown: "周度拆分",
    monthlyBreakdown: "月度拆分",
    periodLabel: "周期",
    tokensLabel: "Token",
    sessionsLabel: "会话",
    activeDaysLabel: "活跃天数",
    peakDayLabel: "峰值日",
    shareLabel: "精确占比",
    sortByLabel: "排序",
    sortRecent: "最近",
    sortTokens: "按 Token",
    sortCost: "按费用",
    subagentsLabel: (count) => `${count} 个子 agent`,
    hideSubagents: "收起子 agent",
    subagentTag: (label) => (label ? `子 agent · ${label}` : "子 agent"),
    billingTitle: "计费状态",
    billingUsage: "额度使用",
    billingUpdated: "更新时间",
    sourceUnavailable: "这个来源的详情暂时不可用",
    noSourceSessions: "这个来源下面还没有索引到 session",
    refresh: "刷新",
    refreshing: "扫描中…",
    lastScan: (t) => `上次扫描 ${t}`,
    waitingScan: "等待首次扫描",
    refreshFailed: "刷新失败 · 将自动重试"
  }
};
